#!/usr/bin/env python3
"""
Build a single PDF from the Open-FDD automated testing docs.

Collects docs/*.md (respecting nav_order and parent from YAML front matter),
strips front matter, concatenates with headings, and runs Pandoc to produce
pdf/open-fdd-automated-testing-docs.pdf. Also writes a .txt file with the same
combined content for LLM / agent context reuse.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from datetime import datetime
from pathlib import Path

try:
    import yaml
except ImportError:
    yaml = None

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
DOCS_DIR = REPO_ROOT / "docs"
PDF_DIR = REPO_ROOT / "pdf"
BUILD_DIR = DOCS_DIR / "_build"
DEFAULT_OUTPUT = PDF_DIR / "open-fdd-automated-testing-docs.pdf"


def parse_front_matter(path: Path) -> tuple[dict, str]:
    text = path.read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}, text
    end = None
    for i in range(1, min(len(lines), 30)):
        if lines[i].strip() == "---":
            end = i
            break
    if end is None:
        return {}, text
    yaml_block = "\n".join(lines[1:end])
    body = "\n".join(lines[end + 1 :]).lstrip()
    try:
        fm = yaml.safe_load(yaml_block) if yaml_block.strip() else {}
    except Exception:
        fm = {}
    return (fm or {}), body


def collect_md_files(docs_dir: Path) -> list[Path]:
    out: list[Path] = []
    for f in sorted(docs_dir.rglob("*.md")):
        if f.name == "404.md":
            continue
        if "_build" in f.parts:
            continue
        out.append(f)
    return out


def build_title_to_nav(files: list[Path]) -> dict[str, int]:
    title_to_nav: dict[str, int] = {}
    for path in files:
        fm, _ = parse_front_matter(path)
        title = fm.get("title")
        nav = fm.get("nav_order")
        if title and nav is not None:
            try:
                title_to_nav[title] = int(nav)
            except (TypeError, ValueError):
                pass
    return title_to_nav


def section_order_key(path: Path, front_matter: dict, title_to_nav: dict[str, int]) -> tuple[int, int, str]:
    parent = front_matter.get("parent") or ""
    nav = front_matter.get("nav_order")
    if nav is None:
        nav = 999
    try:
        nav = int(nav)
    except (TypeError, ValueError):
        nav = 999
    section_nav = title_to_nav.get(parent, nav if not parent else 999)
    return (section_nav, nav, str(path))


def main() -> int:
    parser = argparse.ArgumentParser(description="Build automated testing docs into a single PDF.")
    parser.add_argument("--output", "-o", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--pdf-engine", choices=["weasyprint", "pdflatex", "xelatex"], default="weasyprint")
    parser.add_argument("--no-pdf", action="store_true")
    args = parser.parse_args()

    if yaml is None:
        print("PyYAML is required. pip install pyyaml", file=sys.stderr)
        return 1
    if not DOCS_DIR.is_dir():
        print(f"Docs directory not found: {DOCS_DIR}", file=sys.stderr)
        return 1

    files = collect_md_files(DOCS_DIR)
    title_to_nav = build_title_to_nav(files)
    sorted_files = sorted(files, key=lambda p: section_order_key(p, parse_front_matter(p)[0], title_to_nav))

    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    combined_path = BUILD_DIR / "combined.md"
    build_date = datetime.now().strftime(f"%B {datetime.now().day}, %Y")
    parts: list[str] = []
    parts.append("% Open-FDD Automated Testing Documentation\n")
    parts.append("% Generated by scripts/build_docs_pdf.py\n")
    parts.append(f"% {build_date}\n\n")
    parts.append(f"*Generated {build_date}*\n\n---\n\n")

    for path in sorted_files:
        fm, body = parse_front_matter(path)
        if fm.get("nav_exclude"):
            continue
        title = fm.get("title") or path.stem.replace("-", " ").replace("_", " ").title()
        parts.append(f"# {title}\n\n")
        parts.append(body)
        if not body.endswith("\n"):
            parts.append("\n")
        parts.append("\n\n")

    combined_md = "".join(parts)
    combined_path.write_text(combined_md, encoding="utf-8")
    print(f"Wrote combined markdown to {combined_path}")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    txt_output = args.output.with_suffix(".txt")
    txt_output.write_text(combined_md, encoding="utf-8")
    print(f"Wrote text context to {txt_output}")

    if args.no_pdf:
        print("Skipping PDF (--no-pdf).")
        return 0

    cmd = [
        "pandoc",
        str(combined_path),
        "-o",
        str(args.output),
        "--toc",
        "--number-sections",
        f"--pdf-engine={args.pdf_engine}",
        "-V",
        "documentclass=article",
        "-V",
        "papersize=letter",
        "-V",
        "geometry:margin=1in",
        "-V",
        f"date={build_date}",
    ]
    print("Running:", " ".join(cmd))
    try:
        subprocess.run(cmd, check=True)
    except FileNotFoundError:
        print("pandoc not found on PATH", file=sys.stderr)
        return 1
    except subprocess.CalledProcessError as e:
        print(f"pandoc failed with exit code {e.returncode}", file=sys.stderr)
        return e.returncode

    print(f"Wrote PDF to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
